export {default as Login} from './login'
export {default as Posts} from './posts'
export {default as Profile} from './profile'
export {default as Register} from './register'
export {default as Logout} from './logout'
export {default as NewPost} from './newpost'